name: Validate Packs
on: [push]
jobs:
  validate-packs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Validate Resource Pack
        uses: MrKinau/ResourcePackValidator@v1
        with:
          resourcepack: arloheim-resource-pack
          config: validate-resource-pack-config.json
